#!/bin/bash
set -euo pipefail

# setup-underlay.sh - Set up underlay infrastructure for OpenPERouter (ISIS + SRv6)
#
# This script:
# 1. Waits for FRR container to be ready
# 2. Waits for br0/br-ex to acquire an IP
# 3. Derives node index (last octet) and loopback IPv6 from the br0 IP
# 4. Saves variables for config generation
#
# Usage: Executed by systemd service setup-underlay.service
#
# Exit codes:
#   0   - Success
#   1   - General error
#   124 - Timeout waiting for FRR

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source common utilities
if [[ ! -f "$SCRIPT_DIR/openperouter-common.sh" ]]; then
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] ERROR: openperouter-common.sh not found at $SCRIPT_DIR/openperouter-common.sh" >&2
    exit 1
fi

source "$SCRIPT_DIR/openperouter-common.sh"

# Load environment configuration file
ENV_FILE="${ENV_FILE:-/etc/openperouter/vpn-setup.env}"
if [[ -f "$ENV_FILE" ]]; then
    source "$ENV_FILE"
fi

# Verify required functions
for func in frr_netns_pid inns isfrr_ready; do
    if ! declare -f "$func" >/dev/null 2>&1; then
        echo "[$(date +'%Y-%m-%d %H:%M:%S')] ERROR: Required function $func not found in openperouter-common.sh" >&2
        exit 1
    fi
done

# Load environment variables with defaults

FRR_READY_TIMEOUT="${FRR_READY_TIMEOUT:-60}"

# Output file for variables
VARS_FILE="${VARS_FILE:-/var/lib/openperouter/vpn-setup.vars}"

# Start main execution
log "Starting underlay setup (ISIS + SRv6 mode)"

#
# STEP 1: Wait for FRR container to be ready
#
log_step "Waiting for FRR container"
log "Timeout configured: ${FRR_READY_TIMEOUT}s"
ELAPSED=0
INTERVAL=2

while ! isfrr_ready 2>/dev/null; do
    if [ $ELAPSED -ge $FRR_READY_TIMEOUT ]; then
        error "FRR not ready after ${FRR_READY_TIMEOUT}s timeout"
        error "Check FRR container: podman ps | grep frr"
        error "Check FRR logs: podman logs frr"
        exit_timeout
    fi
    if [ $((ELAPSED % 10)) -eq 0 ] && [ $ELAPSED -gt 0 ]; then
        log "Still waiting for FRR... (${ELAPSED}s elapsed)"
    fi
    sleep $INTERVAL
    ELAPSED=$((ELAPSED + INTERVAL))
done

log "FRR container is ready"

#
# STEP 2: Derive addressing from br0 (or br-ex after OVN takes over)
#
log_step "Deriving addressing from bridge interface"

BR0_READY_TIMEOUT="${BR0_READY_TIMEOUT:-120}"
BR0_ELAPSED=0
BR0_INTERVAL=2
BR0_IP=""
BRIDGE_IFACE=""

while [[ -z "$BR0_IP" ]]; do
    for iface in br0 br-ex; do
        if ip link show "$iface" >/dev/null 2>&1; then
            BR0_IP=$(ip -4 addr show "$iface" | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1 || true)
            if [[ -n "$BR0_IP" ]]; then
                BRIDGE_IFACE="$iface"
                break
            fi
        fi
    done
    if [[ -n "$BR0_IP" ]]; then
        break
    fi
    if [ $BR0_ELAPSED -ge $BR0_READY_TIMEOUT ]; then
        error "No bridge interface (br0/br-ex) has an IP after ${BR0_READY_TIMEOUT}s"
        error "Check: ip addr show br0; ip addr show br-ex"
        exit_error "Bridge interface must have an IP address configured"
    fi
    if [ $((BR0_ELAPSED % 10)) -eq 0 ] && [ $BR0_ELAPSED -gt 0 ]; then
        log "Waiting for bridge IP address... (${BR0_ELAPSED}s elapsed)"
    fi
    sleep $BR0_INTERVAL
    BR0_ELAPSED=$((BR0_ELAPSED + BR0_INTERVAL))
done

# Extract last octet — used as node index for all addressing
LAST_OCTET=$(echo "$BR0_IP" | cut -d. -f4)

# Derive addresses from node index
# LOOPBACK_V6="fd00::${LAST_OCTET}"

BR0_IP_V6=""
BR0_V6_ELAPSED=0
while [[ -z "$BR0_IP_V6" ]]; do
    BR0_IP_V6=$(ip -6 addr show "$BRIDGE_IFACE" scope global | grep -oP '(?<=inet6\s)[0-9a-f:]+' | head -1 || true)
    if [[ -n "$BR0_IP_V6" ]]; then
        break
    fi
    if [ $BR0_V6_ELAPSED -ge $BR0_READY_TIMEOUT ]; then
        log "WARNING: No IPv6 address on $BRIDGE_IFACE after ${BR0_READY_TIMEOUT}s — continuing without it"
        break
    fi
    if [ $((BR0_V6_ELAPSED % 10)) -eq 0 ] && [ $BR0_V6_ELAPSED -gt 0 ]; then
        log "Waiting for bridge IPv6 address... (${BR0_V6_ELAPSED}s elapsed)"
    fi
    sleep $BR0_INTERVAL
    BR0_V6_ELAPSED=$((BR0_V6_ELAPSED + BR0_INTERVAL))
done

log "Bridge interface: $BRIDGE_IFACE, IP: $BR0_IP, IPv6: ${BR0_IP_V6:-none}"
log "Node index (last octet): $LAST_OCTET"
# log "  Loopback IPv6: $LOOPBACK_V6"

#
# STEP 5: Save variables for config generation
#
log_step "Saving variables for config generation"

# Create directory if needed
mkdir -p "$(dirname "$VARS_FILE")"

# Write variables (will be sourced by generate-config.sh)
cat > "$VARS_FILE" <<EOF
# OpenPERouter VPN Setup Variables (ISIS + SRv6)
# Generated by setup-underlay.sh on $(date +'%Y-%m-%d %H:%M:%S')

LAST_OCTET="$LAST_OCTET"
# LOOPBACK_V6="\$LOOPBACK_V6"

EOF

chmod 644 "$VARS_FILE"

log "Variables saved to $VARS_FILE"

exit_success "Underlay setup completed successfully"
